config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :jobs, only: [:index, :show, :new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create]
  resources :comments, only: [:create, :destroy]


  scope "(:locale)", locale: /en|fr/ do
    root to: 'home#index'
  end

  if Rails.env.development?
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :job
  belongs_to :user

  validates :comment, presence: true
  validates :comment, length: { maximum: 255 }

end

app/models/job.rb
class Job < ApplicationRecord

  belongs_to :user

  has_many :comments

  validates :title, :description, presence: true
  validates :title, length: { maximum: 255 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :comments

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :username, length: {maximum: 255, minimum: 4}




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])

  end


  def page_not_found
    respond_to do |format|
      format.html { render template: 'errors/not_found_error', layout: 'layouts/application', status: 404 }
      format.all  { render nothing: true, status: 404 }
    end
  end

  def server_error
    respond_to do |format|
      format.html { render template: 'errors/internal_server_error', layout: 'layouts/error', status: 500 }
      format.all  { render nothing: true, status: 500}
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_comment, only: [:destroy]

  def index

  end

  def show

  end

  def new

  end

  def create

    commentcreate = Comment.create(comments_params)


    redirect_back(fallback_location:root_path) if commentcreate.persisted?

  end

  def edit

  end

  def update

  end

  def destroy
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def comments_params
    params.require(:comment).permit!
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @jobs = Job.all
  end



end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :find_job, only: [:show, :destroy]

  def index
    @jobs = Job.all
  end

  def show
    @comments = @job.comments
    @comment = Comment.new
  end

  def new
    @job = Job.new
  end

  def create
    jobtest = Job.create(jobs_params)

    #if jobtest.persisted?
      #redirect_to root_path
    #end
    redirect_to root_path if jobtest.persisted?

  end

  def edit
    @job = Job.find(1)
  end

  def update

  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private
  def jobs_params
    params.require(:job).permit!
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @jobs = @user.jobs
  end

  def new
    @user = User.new
  end

  def create
    usertest = User.create(user_params)

    redirect_to root_path if usertest.persisted?
  end

  def edit
    @users = User.find(1)
  end

  def update

  end

  def destroy
    @users = User.find(1)
  end


  private
  def user_params
    params.require(:user).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3 class="center-align"><%= t('views.index.home.welcome') %></h3>

<h5 class="center-align"><%= t('views.index.home.id')%> <%= current_user.username %> </h5>

<h4 class="center-align"><%= t('views.index.home.latest') %></h4>



<div class="row">

  <% @jobs.last(4).reverse.each do |job| %>

  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= job.title %></span>
        <p><%= job.description %></p>
        <p><%= job.salaire_moyen %>€</p>
        <p><strong><%= job.company_name %></strong></p>
      </div>
      <div class="card-action">
        <%= link_to t('views.index.home.link'), job_path(job.id) %>
      </div>
    </div>
  </div>

  <% end %>

</div>

app/views/jobs/index.html.erb
<h1>All Jobs</h1>

<ul>

    <% @jobs.each do |job| %>

    <li><strong><%= t('views.index.jobs.job') %> : </strong> <%= job.title %></li>
    <li><strong>Description :</strong> <%= job.description %></li>
    <li><strong><%= t('views.index.jobs.salary') %> : </strong> <%= job.salaire_moyen %>€</li>
    <li><strong><%= t('views.index.jobs.by') %> : </strong> <%= job.company_name %></li>

    <br>
    <%= link_to t('views.index.home.link'), job_path(job.id) %>
    <br>
    <hr>

    <% end %>

</ul>

app/views/jobs/new.html.erb
<h1><%= t('views.new.jobs.offer') %> : </h1>
<%= form_for @job do |f| %>

  <%= f.label t('views.new.jobs.title') %> <br>
  <%= f.text_field :title, placeholder: t('views.new.jobs.title'), required: true %> <br>

  <%= f.label 'Description' %> <br>
  <%= f.text_area :description, placeholder: 'Description', required: true %> <br>

  <%= f.label t('views.new.jobs.company') %> <br>
  <%= f.text_field :company_name, placeholder: t('views.new.jobs.company') %> <br>

  <%= f.label t('views.new.jobs.salary') %> <br>
  <%= f.text_field :salaire_moyen, placeholder: t('views.new.jobs.salary') %> <br>

  <%= f.hidden_field :user_id, value: current_user.id %> <br>

  <%= f.submit t('views.new.jobs.submit'), :class => 'waves-effect waves-light btn' %> <br>

<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><strong>Description :</strong> <%= @job.description %></p>
<p><strong><%= t('views.show.jobs.salary') %> :</strong> <%= @job.salaire_moyen %></p>
<p><strong><%= t('views.show.jobs.company') %> :</strong> <%= @job.company_name %></p>

<br>

<% if @job.user_id === (current_user.id).to_s %>
  <%= link_to t('views.show.jobs.delete'), job_path(@job), method: :delete, class: 'waves-effect waves-light btn red' %>
<% end %>
<br>
<hr>

<h4><%= t('views.show.jobs.comment') %> : </h4>
<%= form_for @comment do |f| %>

  <%= f.label t('views.show.jobs.comment') %> <br>
  <%= f.text_area :comment, placeholder: t('views.show.jobs.comment'), required: true %> <br>
  <%= f.hidden_field :user_name, value: current_user.username %> <br>
  <%= f.hidden_field :job_id, value: @job.id %> <br>
  <%= f.hidden_field :user_id, value: current_user.id %> <br>
  <br>
  <%= f.submit t('views.show.jobs.submit'), :class => 'waves-effect waves-light btn' %> <br>

<% end %>

<br>

<h3 class="light-blue-text"><%= t('views.show.jobs.section') %></h3>
<hr>
<br>

<% @comments.each do |com| %>

  <div><%= com.comment %></div>
  <div><%= t('views.show.jobs.by') %> : <%= com.user_name %></div>

  <% if current_user == com.user || current_user == @job.user %>
  <%= link_to t('views.show.jobs.deletecomment'), comment_path(com), method: :delete, class: 'waves-effect waves-light btn red' %>
  <% end %>

  <hr>
  <br>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'materialize.min' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'materialize.min' %>

  </head>

  <body>

    <%= render partial: 'shared/menu' %>
    <div class="container">
      <div class="row">
        <div class="col s12">

        <%= yield %>

        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= action_name.titleize %> :: <%= site_name %></title>
  <%= csrf_meta_tags %>
  <style>
    body {
      background: #fff;
      font-family: Helvetica, Arial, Sans-Serif;
      font-size: 14px;
    }
    .error_container {
      display: block;
      margin: auto;
      margin: 10% auto 0 auto;
      width: 40%;
    }
    .error_container .error {
      display: block;
      text-align: center;
    }
    .error_container .error img {
      display: block;
      margin: 0 auto 25px auto;
    }
    .error_container .message strong {
      font-weight: bold;
      color: #f00;
    }
    .error_container .contact_info {
      display: block;
      text-align: center;
      margin: 25px 0 0 0;
    }
    .error_container .contact_info a {
      display: inline-block;
      margin: 0 5px;
      opacity: 0.4;
      transition: opacity 0.15s ease;
    }
    .error_container .contact_info a:hover {
      opacity: 0.8;
    }
  </style>
</head>
<body>
<div class="error_container">
  <%= yield %>
</div>
</body>
</html>

app/views/shared/_menu.html.erb
<nav>
    <div class="nav-wrapper">
      <ul class="left hide-on-med-and-down">
        <li>
          <%= link_to t('views.menu.home'), root_path %>
        </li>
        <li>
          <%= link_to t('views.menu.all_jobs'), jobs_path %>
        </li>
        <li>
          <%= link_to t('views.menu.all_users'), users_path %>
        </li>
        <li>
          <%= link_to t('views.menu.my_jobs'), user_path(current_user) unless current_user.nil? %>
        </li>
        <li>
          <%= link_to t('views.menu.create_job'), new_job_path %>
        </li>
        <li>
          <%= link_to t('views.menu.sign_out'), destroy_user_session_path, method: :delete, :class => 'blue-grey-text' %>
        </li>
        <li>
          <%=link_to 'En', locale: 'en' %>
        </li>
        <li>
          |
        </li>
        <li>
          <%=link_to 'Fr', locale: 'fr' %>
        </li>
      </ul>
    </div>
</nav>

app/views/users/index.html.erb
<h1>Index Users</h1>

<ul>

<% @users.each do |user| %>

   <li><%= user.username %></li>
    <%= link_to t('views.index.users.link'), user_path(user.id) %>
    <br>
    <hr>
    <br>
<% end %>

</ul>

app/views/users/new.html.erb
<h1>Créer une nouvelle offre d'emploi : </h1>
<%= form_for @user do |f| %>

  <%= f.label 'Username' %> <br>
  <%= f.text_field :username, placeholder: 'Username' %> <br>

  <%= f.label 'Email' %> <br>
  <%= f.text_field :email, placeholder: 'Email' %> <br>

  <%= f.submit 'Envoyer' %> <br>

<% end %>

app/views/users/show.html.erb
<h3 class="center-align"><%= current_user == @user ? t('views.show.users.my') : "#{@user.username}'s jobs" %></h3>


<% @jobs.each do |job| %>

  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= job.title %></span>
        <p><%= job.description %></p>
        <p><%= job.salaire_moyen %>€</p>
        <p><strong><%= job.company_name %></strong></p>
      </div>
      <div class="card-action">
        <%= link_to t('views.show.users.link'), job_path(job.id) %>
      </div>
    </div>
  </div>

<% end %>